### ISSUE TITLE
Use Zstandard (ZSTD) instead of ZLib

### ISSUE THREAD

**Issue by dforsber** [ryanhomer/sqlite3-compression-encryption-vfs#6]
[ZSTD compression algorithm is much better than zlib](http://facebook.github.io/zstd/) and would probably make more sense to use as the default choice of algorithm?

**Comment by techrah** [comment]
There is no default compression built in. You need to supply your own compression library. References to zlib were only for illustration purposes. If you want to use Zstandard, you could try something like this using the sample  code in `xMethods.c`:

```c
#import <zstd.h>

int cevfsCompressBound(void *p, size_t nByte) {
  return (int)ZSTD_compressBound(nByte);
}

int cevfsCompress(void *p, char *aDest, size_t *pnDest, char *aSrc, size_t nSrc) {
  *pnDest = ZSTD_compress(aDest, *pnDest, aSrc, nSrc, 0);
  return !ZSTD_isError(*pnDest);
}

int cevfsUncompress(void *p, char *aDest, size_t *pnDest, char *aSrc, size_t nSrc) {
  *pnDest = ZSTD_decompress(aDest, *pnDest, aSrc, nSrc);
  return !ZSTD_isError(*pnDest);
}
```

and link to the Zstandard library with `-lzstd` instead of `-lz`
